### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [naganoj/teacozy#6]
Grade: Satisfactory

Summary: Nice job on this project, the page looks good. You used some clever techniques and kept your code well organized. I would take a look at the issues I created as it addresses some minor tweaks for best practices. Overall everything looks good, just some minor adjustments could be made. I would look up some common css naming conventions if you have interest/time, I like BEM: 
http://getbem.com/introduction/

**Comment by naganoj** [comment]
Thank you for the feedback.  It is very helpful.
